#spring.application.name=backend

# ===============================
# DATABASE CONFIGURATION
# ===============================

#spring.datasource.url=jdbc:postgresql://localhost:5432/crowdfund

#spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/crowdfund
spring.datasource.url=jdbc:postgresql://localhost:5432/crowdfund
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver


# ===== JWT =====
jwt.secret=9f826d3b4e5a1c7f0d8e2b3a4f5c6e7d8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d
#jwt secrete = 9f826d3b4e5a1c7f0d8e2b3a4f5c6e7d8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d

# ===============================
# JPA / HIBERNATE CONFIGURATION
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# SERVER PORT (optional)
# ===============================

server.port=8080

# ===============================
# RAZORPAY
# ===============================

razorpay.key.id=rzp_test_SN8w1CRy6KFPz6
razorpay.key.secret=qa0Y6sGwtakh93r4Ptd2VsxK
razorpay.webhook.secret= i6@5@PgfHYvWnHB 


cloudinary.cloud-name=dd3g7mlkl
cloudinary.api-key=139563786914658
cloudinary.api-secret=3DRX2de8cr59CWFxagHNRjaD2iI
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


# == Redis ==
spring.cache.type=redis
spring.redis.host=localhost
spring.redis.port=6379